<a href="https://colab.research.google.com/github/sakthikaruna29-lgtm/Python-Learning-DE/blob/main/Sep_5%2C_2026_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
# Array Creation

In [ ]:
arr=np.array([1,2,3])
print (arr)
arr.ndim

[1 2 3]


1

In [ ]:
a=np.array([[1,2,3],[1,2,3]])
print(a)
a.ndim

[[1 2 3]
 [1 2 3]]


2

In [ ]:
b=np.array([[[1,2,3],[1,2,3]],[[1,5,4],[1,4,5]]])
print(b)
b.ndim

[[[1 2 3]
  [1 2 3]]

 [[1 5 4]
  [1 4 5]]]


3

In [ ]:
# Array Creation Methods

In [ ]:
c=np.array([1,2,3])
d=np.zeros(5)
e=np.ones(4,dtype=int) # Print 1D array with 1 as value for 4 columns
f=np.arange(1,10) #1 to 9
g=np.linspace(1,10,3) # 3 evenly spaced value

print(c)
print(d)
print(e)
print(f)
print(g)

[1 2 3]
[0. 0. 0. 0. 0.]
[1 1 1 1]
[1 2 3 4 5 6 7 8 9]
[ 1.   5.5 10. ]


In [ ]:
# Shapes and Dimensions Methods

In [ ]:
fl=np.array([[19,3,134],[2,43,22]])
print(fl.shape)
print(fl.ndim)
print(fl.size)
print(fl.reshape(6,1))
print(fl.flatten())

(2, 3)
2
6
[[ 19]
 [  3]
 [134]
 [  2]
 [ 43]
 [ 22]]
[ 19   3 134   2  43  22]


In [ ]:
# Mathematical Methods

In [ ]:
print(fl.sum())
print(fl.mean())
print(fl.max())
print(fl.min())
print(fl.std())
print(fl.var())

55
9.166666666666666
23
1
7.924995618645828
62.805555555555564


In [ ]:
# Sorting Methods

In [ ]:
print(np.sort(fl))
print(np.argsort(fl))

[[  3  19 134]
 [  2  22  43]]
[[1 0 2]
 [0 2 1]]


In [ ]:
# Joining and Splitting Arrays

In [ ]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[8,3,2],[4,6,5]])

print("Concatenate:", np.concatenate((a,b)))
print("vstack", np.vstack((a,b)))
print("hstack",np.hstack((a,b)))

Concatenate: [[1 2 3]
 [3 4 5]
 [8 3 2]
 [4 6 5]]
vstack [[1 2 3]
 [3 4 5]
 [8 3 2]
 [4 6 5]]
hstack [[1 2 3 8 3 2]
 [3 4 5 4 6 5]]
